version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: notification_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-notification_system}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - notification_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-notification_system}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  notification_network:
    driver: bridge
volumes:
  postgres_data:
